apiVersion: v1
kind: Service
metadata:
  name: servicecatalog-service
  labels:
    app: servicecatalog
spec:
  selector:
    app: servicecatalog
  ports:
    - name: http
      port: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: servicecatalog-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /servicecatalog/(.*)
          backend:
            serviceName: servicecatalog-service
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicecatalog
  labels:
    app: servicecatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicecatalog
  template:
    metadata:
      labels:
        app: servicecatalog
    spec:
      containers:
      - name: servicecatalog
        image: masterarbeithhz/thesis:servicecatalogv1
