apiVersion: v1
kind: Service
metadata:
  name: dprocess-service
  labels:
    app: dprocess
spec:
  selector:
    app: dprocess
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32221
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dprocess
  labels:
    app: dprocess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dprocess
  template:
    metadata:
      labels:
        app: dprocess
    spec:
      containers:
      - name: dprocess
        image: masterarbeithhz/thesis:processv2
