apiVersion: v1
kind: Service
metadata:
  name: dprocess-service
  labels:
    app: dprocess
spec:
  selector:
    app: dprocess
  ports:
    - name: http
      port: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: verarbeitung-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /verarbeitung/(.*)
          backend:
            serviceName: dprocess-service
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dprocess
  labels:
    app: dprocess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dprocess
  template:
    metadata:
      labels:
        app: dprocess
    spec:
      containers:
      - name: dprocess
        image: masterarbeithhz/thesis:processv5
