apiVersion: v1
kind: Service
metadata:
  name: ucadmin-service
  labels:
    app: ucadmin
spec:
  selector:
    app: ucadmin
  ports:
    - name: http
      port: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ucadmin-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /verwaltung/(.*)
          backend:
            serviceName: ucadmin-service
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucadmin
  labels:
    app: ucadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucadmin
  template:
    metadata:
      labels:
        app: ucadmin
    spec:
      containers:
      - name: ucadmin
        image: masterarbeithhz/thesis:ucadminv6
        ports:
        - containerPort: 80
