apiVersion: v1
kind: Service
metadata:
  name: dvisual-service
  labels:
    app: dvisual
spec:
  selector:
    app: dvisual
  ports:
    - name: http
      port: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dvisual-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /visualisierung/(.*)
          backend:
            serviceName: dvisual-service
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvisual
  labels:
    app: dvisual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvisual
  template:
    metadata:
      labels:
        app: dvisual
    spec:
      containers:
      - name: dvisual
        image: masterarbeithhz/thesis:visualv3
