apiVersion: v1
kind: Service
metadata:
  name: dvisual-service
  labels:
    app: dvisual
spec:
  selector:
    app: dvisual
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32222
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvisual
  labels:
    app: dvisual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvisual
  template:
    metadata:
      labels:
        app: dvisual
    spec:
      containers:
      - name: dvisual
        image: masterarbeithhz/thesis:visualv2
